nginx:
  image: "nginx:1.11.10"
  ports:
    - 5043:443
  links:
    - registry:registry
  volumes:
    - /root/ci/nginx/auth:/etc/nginx/conf.d
    - /root/ci/nginx/auth/nginx.conf:/etc/nginx/nginx.conf:ro

registry:
  image: "registry:2.6.0"
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - /root/ci/registry/data:/var/lib/registry