#!/bin/bash
#chkconfig: 2345 80 90
#description:auto_run

#------------------------------------------------------------------------------
#该文件需指定到/etc/rc.d/init.d文件夹下,默认开机启动
#执行命令：
#chmod +x jenkins
#chkconfig --add jenkins
#------------------------------------------------------------------------------

start() {
	echo 'jenkins start...'
	/usr/local/apache-tomcat-jenkins/bin/startup.sh
	#nohup java -server -Xmx3550m -Xms3550m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -jar /usr/local/jenkins.war > /var/log/jenkins.log 2>&1 & echo $! > /var/run/jenkins.pid
	echo 'jenkins start success!'
}

stop() {
	echo 'jenkins stop...'
	kill `cat /var/run/jenkins.pid`
	/usr/local/apache-tomcat-jenkins/bin/shutdown.sh
	echo 'jenkins stop success'
}
#------------------------------------------------------------------------------
case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0